<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-10-23 12:05+0000
// PO revision date:  2012-09-17 14:22+0000
$lang = array(
	
	'form_placa_cars' => 'Numero de Placa del Vehiculo',
	'form_descr_cars' => 'Descripcion del Vehiculo',
	'form_marca_cars' => 'Marca del Vehiculo',
	'form_modelo_cars' => 'Modelo del Vehiculo',
	'form_nombre_persons' => 'Nombre',
	'form_documento_persons' => 'Documento',
	'form_cargo_persons' => 'Cargo',
	'menu_gestion' => 'Gestion',
	'menu_cars' => 'Vehiculos',
	'menu_persons' => 'Personas',
	'menu_instalacion' => 'Instalacion Sanitaria',
	'header_cars' => 'Placa Vehiculo',
	'header_placacars' => 'Placa Vehiculo',	
	'header_descr_cars' => 'Descripcion',
	'header_persons' => 'Persona',
	'header_nompersons' => 'Nombre',	
	'header_cargopersons' => 'Cargo',
	'form_institucionsolicitante' => 'Institucion solicitante',
	'form_ubicacion_emblema' => 'Ubicacion Emblema',
	'form_nombre_prestador_servicio' => 'Nombre Prestador de Servicio',
	'form_tipo_empresa' => 'Tipo de Empresa',
	'form_direccion_prestardor_servicio' => 'Direcccion Prestador de Servicio',
	'form_telefono_prestador_servicio' => 'Telefono Prestador de Servicio',
	'form_perfil_institucional' => 'Perfil Institucional',
	'form_otro_perfil_institucional' => 'Otro Perfil Institucional',
	'form_nombre_representante_legal' => 'Nombre Representante Legal',
	'form_correo_representante_legal' => 'Correo Representante Legal',
	'form_cargo_representante_legal' => 'Cargo Representante Legal',
	'header_institucionsolicitante' => 'Institucion Sololicitante',
	'header_ubicacion_emblema' => 'Ubicacion Emblema'

);
